Secure Admin Page and Press API
BioTork/WebApp pull request #15
Opened 2019-11-25 03:11 UTC by jm52262

2019-11-25 19:42 UTC, arsenalgunnershubert777 commented on server/controllers/press.server.controller.js
> +  if(req.isAuthrnticated){
mispelled Authenticated

2019-11-25 19:42 UTC, arsenalgunnershubert777 requested changes
one place mispelled isAuthenticated

2019-11-26 05:01 UTC, jm52262 commented on server/controllers/press.server.controller.js
> +  if(req.isAuthrnticated){
Corrected

2019-11-27 04:47 UTC, arsenalgunnershubert777 commented on server/controllers/press.server.controller.js
> +  if(req.isAuthrnticated){
typo here as well

2019-11-27 04:49 UTC, arsenalgunnershubert777 requested changes
one more typo

2019-11-27 17:27 UTC, arsenalgunnershubert777 approved these changes
looks good

2019-11-27 20:22 UTC, merged